### ISSUE TITLE
There was a mass blocking

### ISSUE THREAD

**Issue by ToasterWaffl** [QuiteAFancyEmerald/Holy-Unblocker-Old#353]
On my end 10 different sites are currently blocked

**Comment by 3L33tmakersUnited** [comment]
Sorry but all of the sites have ended and we hope more will happen on another group.

**Comment by Zubbbz** [comment]
this is not an issue for the developer. They just make the project. They cannot control who does and doesn't block their website. Host it yourself if you are able to, google cloud should be a pretty safe option.
